name: Build on push

permissions:
  packages: write

on:
    push:
        branches:
            - main
            - master
            - develop

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build client images
        run: |
                docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$BRANCH \
                --output "type=registry" ./
